export default {
  DrStrangeTwo: {
    show: {
      type: 'Movie',
      name: 'Doctor Strange in the Multiverse of Madness',
      releaseYear: 2022,
      length: 126,
      summary:
        'Doctor Strange teams up with a mysterious teenage girl from his dreams who can travel across multiverses, to battle multiple threats, including other-universe versions of himself, which threaten to wipe out millions across the multiverse. They seek help from Wanda the Scarlet Witch, Wong and others.',
      pgRating: 'PG-13',
      movie: {
        budget: 200000000,
        revenue: 955152198,
        urls: [
          {
            serverName: 'membed',
            url: 'https://streamsss.net/e/kqg5h36dg3cv?caption_1=https://msubload.com/sub/doctor-strange-in-the-multiverse-of-madness/doctor-strange-in-the-multiverse-of-madness.v19.vtt&sub_1=English',
          },
        ],
      },
    },
    servers: [{ name: 'membed', url: 'https://membed.net/encrypt-ajax.php' }],
    imdb: { imdbId: 'tt9419884', rating: 7, voteCount: 382000 },
    images: [
      {
        url: 'https://m.media-amazon.com/images/M/MV5BNWM0ZGJlMzMtZmYwMi00NzI3LTgzMzMtNjMzNjliNDRmZmFlXkEyXkFqcGdeQXVyMTM1MTE1NDMx._V1_QL75_UX380_CR0,0,380,562_.jpg',
        type: 'poster',
        width: null,
        height: null,
        aspectRatio: null,
        isDefault: true,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//wcKFYIiVDvRURrzglV9kGu7fpfY.jpg',
        type: 'backdrop',
        width: 3840,
        height: 2160,
        aspectRatio: 1.778,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//dTn1HGhCuq26IoBq9qKsiYNFxfq.jpg',
        type: 'backdrop',
        width: 3000,
        height: 1688,
        aspectRatio: 1.777,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//aaBEOygdsIZf2a9LOd79hUcZu5n.jpg',
        type: 'backdrop',
        width: 3840,
        height: 2160,
        aspectRatio: 1.778,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//80K8zuNYC2nCwkgzYL8m0btEylp.jpg',
        type: 'backdrop',
        width: 3840,
        height: 2160,
        aspectRatio: 1.778,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//51wwXoVKpS6oJMbz03qvN0Hxt99.jpg',
        type: 'backdrop',
        width: 3840,
        height: 2160,
        aspectRatio: 1.778,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//shDYfjtNFyZmf7uZNtOLaI6iJXM.jpg',
        type: 'backdrop',
        width: 3840,
        height: 2160,
        aspectRatio: 1.778,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//tB431i0Mjq4chHEuQ4O3e6SECNo.jpg',
        type: 'backdrop',
        width: 3840,
        height: 2160,
        aspectRatio: 1.778,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//y8FWxsXAumD2cEmPSDDM1aNgGYo.jpg',
        type: 'backdrop',
        width: 3840,
        height: 2160,
        aspectRatio: 1.778,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//gUNRlH66yNDH3NQblYMIwgZXJ2u.jpg',
        type: 'backdrop',
        width: 3840,
        height: 2160,
        aspectRatio: 1.778,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//v4ZgR8JXoJJf4Bag1dQCmhPySSh.jpg',
        type: 'backdrop',
        width: 3054,
        height: 1716,
        aspectRatio: 1.78,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//AdyJH8kDm8xT8IKTlgpEC15ny4u.jpg',
        type: 'backdrop',
        width: 3840,
        height: 2160,
        aspectRatio: 1.778,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//6tZeX0gvlPzHU8phHuiZD8Gsa11.jpg',
        type: 'backdrop',
        width: 3840,
        height: 2160,
        aspectRatio: 1.778,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//lv3TXqhpaIxkclIHbhN2MRMOemQ.jpg',
        type: 'backdrop',
        width: 3840,
        height: 2160,
        aspectRatio: 1.778,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//k9v0ZJ54TP0nCbVBZqsC0Q8B9kH.jpg',
        type: 'backdrop',
        width: 2880,
        height: 1620,
        aspectRatio: 1.778,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//wPKhu8NgdMH258ztj4tzqYRBgHS.jpg',
        type: 'backdrop',
        width: 1422,
        height: 800,
        aspectRatio: 1.778,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//7WRQA5R69NqNJqW200WNRWwbwUv.jpg',
        type: 'backdrop',
        width: 1280,
        height: 720,
        aspectRatio: 1.778,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//u08uSW1Kzc2Oe4YkXwjS9awQAKD.jpg',
        type: 'backdrop',
        width: 1280,
        height: 720,
        aspectRatio: 1.778,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//3eQIcFFmlmz8yqGzGq0ZCOOWoFJ.jpg',
        type: 'backdrop',
        width: 1280,
        height: 720,
        aspectRatio: 1.778,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//aiURol0uepOhtJQuup1ayOhSWa5.jpg',
        type: 'backdrop',
        width: 2197,
        height: 1236,
        aspectRatio: 1.778,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//248alQx2wdI4n5SOaNtrA7Znrd9.jpg',
        type: 'backdrop',
        width: 2900,
        height: 1631,
        aspectRatio: 1.778,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//qfN6zIDbCGkZHR2QGAmSBEwNMcU.jpg',
        type: 'backdrop',
        width: 2900,
        height: 1631,
        aspectRatio: 1.778,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//un2j6H12z6xd8gt29dR4nXzvKcX.jpg',
        type: 'backdrop',
        width: 1397,
        height: 786,
        aspectRatio: 1.777,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//p1oWXATsQl1Q204B929eNl2uaDl.jpg',
        type: 'backdrop',
        width: 1401,
        height: 788,
        aspectRatio: 1.778,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//3pjew3SaBuJHoJCvAKgl4knhKiS.jpg',
        type: 'backdrop',
        width: 2560,
        height: 1440,
        aspectRatio: 1.778,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//ndCSoasjIZAMMDIuMxuGnNWu4DU.jpg',
        type: 'backdrop',
        width: 1920,
        height: 1080,
        aspectRatio: 1.778,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//11ZcwW7KqNPwKzFcyFGrA0MBt49.jpg',
        type: 'backdrop',
        width: 2864,
        height: 1609,
        aspectRatio: 1.78,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//fBStjn6y58rZ4QMyMGkodFdEIJa.jpg',
        type: 'backdrop',
        width: 1563,
        height: 878,
        aspectRatio: 1.78,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//zUYGHXnIVkP7HHipLm1P0jhwIbJ.jpg',
        type: 'backdrop',
        width: 3054,
        height: 1716,
        aspectRatio: 1.78,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//5RHc3iiLMQgjNU1mCJ9SM17JQAj.jpg',
        type: 'backdrop',
        width: 2900,
        height: 1631,
        aspectRatio: 1.778,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//4TIRvoMRretogHfr988pdm062Vy.jpg',
        type: 'backdrop',
        width: 3840,
        height: 2160,
        aspectRatio: 1.778,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//i6H0s8nM8dPu3EvcKYi50b69XYU.jpg',
        type: 'backdrop',
        width: 1563,
        height: 878,
        aspectRatio: 1.78,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//gN264FfwGRU0ixdEmMQOjClQ1Kk.jpg',
        type: 'backdrop',
        width: 1944,
        height: 1094,
        aspectRatio: 1.777,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//nfgFyMyewlj1E3RGeHRUWZARJlT.jpg',
        type: 'backdrop',
        width: 3840,
        height: 2160,
        aspectRatio: 1.778,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//d0LfrKXMogbJujV6Mc7L9cUssC8.jpg',
        type: 'backdrop',
        width: 1920,
        height: 1080,
        aspectRatio: 1.778,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//2ylEZweqpESFvGPzR1JDUCEg2pp.jpg',
        type: 'backdrop',
        width: 3840,
        height: 2160,
        aspectRatio: 1.778,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//3NMTImL2NHi7yAfLp7nDPLWmb2I.jpg',
        type: 'backdrop',
        width: 3840,
        height: 2160,
        aspectRatio: 1.778,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//1Rqkk4pfJeq3r8rSob4dsC6xZmD.jpg',
        type: 'backdrop',
        width: 3840,
        height: 2160,
        aspectRatio: 1.778,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//kV3f192Cz9frGWcJUm3YtaYMVNI.jpg',
        type: 'backdrop',
        width: 1280,
        height: 720,
        aspectRatio: 1.778,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//zzFQk6KDMCIhXlUwrhbYTtx8tvA.jpg',
        type: 'backdrop',
        width: 3054,
        height: 1716,
        aspectRatio: 1.78,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//gRxjOxn9n3LoAHg5CqoVIHf9TMp.jpg',
        type: 'backdrop',
        width: 3054,
        height: 1716,
        aspectRatio: 1.78,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//xYajndQR40qWduIScJDEstkftvj.jpg',
        type: 'backdrop',
        width: 3051,
        height: 1716,
        aspectRatio: 1.778,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//x7QlYRm1ALjE5zHs8vEGvvshlWU.jpg',
        type: 'backdrop',
        width: 3054,
        height: 1716,
        aspectRatio: 1.78,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//eX7cLqwWDqjLnZEd2OdvaTx2o5e.jpg',
        type: 'backdrop',
        width: 1920,
        height: 1080,
        aspectRatio: 1.778,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//xvIAeAyXakMHPOgU7URp1kqKQZI.jpg',
        type: 'backdrop',
        width: 3840,
        height: 2160,
        aspectRatio: 1.778,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//opyjgHMHM1q9RsgYuwm2WCiAzkG.jpg',
        type: 'backdrop',
        width: 1525,
        height: 858,
        aspectRatio: 1.777,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//jQ8QGubTbCEcElSPEiySzLYZ2fX.jpg',
        type: 'backdrop',
        width: 3840,
        height: 2160,
        aspectRatio: 1.778,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//2L2cXgUe4BSb3aF8NSWmtocK5UN.jpg',
        type: 'backdrop',
        width: 3840,
        height: 2160,
        aspectRatio: 1.778,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//6do8rlDHJ16DsB449LCe8zf5s8j.jpg',
        type: 'backdrop',
        width: 1280,
        height: 720,
        aspectRatio: 1.778,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//9ii8mNgX8kZd5oJS1NyyfYxFem6.jpg',
        type: 'backdrop',
        width: 3840,
        height: 2160,
        aspectRatio: 1.778,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//gtGUvavuQoc7YKuS1QYXEEeiNXQ.jpg',
        type: 'backdrop',
        width: 3840,
        height: 2160,
        aspectRatio: 1.778,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//4kiwK39g7QtWkl9YhnopnzgHVjn.jpg',
        type: 'backdrop',
        width: 3840,
        height: 2160,
        aspectRatio: 1.778,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//beni5Q18A18DQZOPa7QMC7Wq4nO.jpg',
        type: 'backdrop',
        width: 3840,
        height: 2160,
        aspectRatio: 1.778,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//tPnROETvX2OXqBMiFhH9CY9oiEH.jpg',
        type: 'backdrop',
        width: 3840,
        height: 2160,
        aspectRatio: 1.778,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//2K5KkoKOnQFVgySEnNYIywdU2md.jpg',
        type: 'backdrop',
        width: 3840,
        height: 2160,
        aspectRatio: 1.778,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//w8LBnUgKpK6oiqw87gHSiHgGKRE.png',
        type: 'logo',
        width: 781,
        height: 237,
        aspectRatio: 3.295,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//6Wy7tZQbF9Mm4sD3IaJyVMDIb6u.png',
        type: 'logo',
        width: 3202,
        height: 301,
        aspectRatio: 10.638,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//edRe6zaHvCWMMuoLRWAe5NtWGmV.png',
        type: 'logo',
        width: 3837,
        height: 348,
        aspectRatio: 11.026,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//1ZSID6CsTFrmlogjArLZXuojzy5.png',
        type: 'logo',
        width: 1612,
        height: 814,
        aspectRatio: 1.98,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//omz9LWkZgkAEpHeOOdTzSevwG6I.png',
        type: 'logo',
        width: 3390,
        height: 1008,
        aspectRatio: 3.363,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//uGkbezqylCIVWBScUVTRK8xH7oP.png',
        type: 'logo',
        width: 3391,
        height: 1008,
        aspectRatio: 3.364,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//qSaVT1QmSOdDYDiVYmDerXRhUnI.png',
        type: 'logo',
        width: 777,
        height: 287,
        aspectRatio: 2.707,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//rF8BPkYJ8ZtrEOtc2bY9u4x5l1.png',
        type: 'logo',
        width: 2504,
        height: 768,
        aspectRatio: 3.26,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//srOEnYNts2VJQ1azVoa611GhXdb.png',
        type: 'logo',
        width: 1920,
        height: 1061,
        aspectRatio: 1.81,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//tSRWD1IRDBI7LsRACDIb4ZFD3tT.png',
        type: 'logo',
        width: 892,
        height: 340,
        aspectRatio: 2.624,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//388wNEI2zxVDJRy5k0Tdvo4gFwd.png',
        type: 'logo',
        width: 3391,
        height: 1288,
        aspectRatio: 2.633,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//7FrW8xdtCRuhAm3ihTafJb8oH3J.png',
        type: 'logo',
        width: 3390,
        height: 1288,
        aspectRatio: 2.632,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//9Gtg2DzBhmYamXBS1hKAhiwbBKS.jpg',
        type: 'poster',
        width: 1000,
        height: 1500,
        aspectRatio: 0.667,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//fwBl3J2aEXru6mrr9Xg8O99Iz2K.jpg',
        type: 'poster',
        width: 2000,
        height: 3000,
        aspectRatio: 0.667,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//4PEydC86QahUd5edKrksxpveove.jpg',
        type: 'poster',
        width: 1600,
        height: 2400,
        aspectRatio: 0.667,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//61PVJ06oecwvcBisoAQu6SDfdcS.jpg',
        type: 'poster',
        width: 2000,
        height: 3000,
        aspectRatio: 0.667,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//m2f19zkF4H2KxVe0Xj1yzkDjUA1.jpg',
        type: 'poster',
        width: 1400,
        height: 2100,
        aspectRatio: 0.667,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//A7CzMZBitf00BAtb1kJa50pWPgV.jpg',
        type: 'poster',
        width: 2000,
        height: 3000,
        aspectRatio: 0.667,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//ddJcSKbcp4rKZTmuyWaMhuwcfMz.jpg',
        type: 'poster',
        width: 2000,
        height: 3000,
        aspectRatio: 0.667,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//aB6uuWZkpHoePcARzjCgra2TbD3.jpg',
        type: 'poster',
        width: 1382,
        height: 2074,
        aspectRatio: 0.666,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//sLRBMQ33FE5syEI3Y3GHFA4DfSm.jpg',
        type: 'poster',
        width: 2000,
        height: 3000,
        aspectRatio: 0.667,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//3QEZxV6N45oxKq1PpbjK9mrSLap.jpg',
        type: 'poster',
        width: 1688,
        height: 2500,
        aspectRatio: 0.675,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//dXgz2XooUyXg1j10SstABt2Qx5J.jpg',
        type: 'poster',
        width: 2000,
        height: 3000,
        aspectRatio: 0.667,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//tIXgI7u0gFbn28V0Cu0TOsZSA4Q.jpg',
        type: 'poster',
        width: 1705,
        height: 2560,
        aspectRatio: 0.666,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//vlCLV1bWSoHqzf1xX6Dp1CrCV9B.jpg',
        type: 'poster',
        width: 2000,
        height: 3000,
        aspectRatio: 0.667,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//evqNkeT0xxIXllE36RnrUXuUwDQ.jpg',
        type: 'poster',
        width: 2000,
        height: 3000,
        aspectRatio: 0.667,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//ixKtfcdjqG9boOjd33wy6J9FIA.jpg',
        type: 'poster',
        width: 1000,
        height: 1501,
        aspectRatio: 0.666,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//19VQU3EpNvSpwWnu0KpTaKI0yEy.jpg',
        type: 'poster',
        width: 1402,
        height: 2048,
        aspectRatio: 0.685,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//iDbMihzwn5F4hKjaxNrFTlZSIdQ.jpg',
        type: 'poster',
        width: 2000,
        height: 3000,
        aspectRatio: 0.667,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//fDLvnjo1jbZurPr5a2OmmKxstM8.jpg',
        type: 'poster',
        width: 1000,
        height: 1500,
        aspectRatio: 0.667,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//7uW1912QcmeIZzHR6d6GaSkYpAC.jpg',
        type: 'poster',
        'w2022-09-21T20:16:07.411411531Z idth': 1000,
        height: 1500,
        aspectRatio: 0.667,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//fFLLOFd5WGkwAXxMtDbIi658cuY.jpg',
        type: 'poster',
        width: 2000,
        height: 3000,
        aspectRatio: 0.667,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//S4kaYiFhnf0Bl7OwdbxPWMcQqi.jpg',
        type: 'poster',
        width: 854,
        height: 1280,
        aspectRatio: 0.667,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//ciI8mZKiHfZZv2cjiMVwgcRZIwr.jpg',
        type: 'poster',
        width: 2000,
        height: 3000,
        aspectRatio: 0.667,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//sF0Ciu56om4sTR1KtuZvbUoqKrf.jpg',
        type: 'poster',
        width: 2000,
        height: 3000,
        aspectRatio: 0.667,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//wRnbWt44nKjsFPrqSmwYki5vZtF.jpg',
        type: 'poster',
        width: 2000,
        height: 2962,
        aspectRatio: 0.675,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//ul98Vd3bGY3BBhSeVCbgiutC3Jk.jpg',
        type: 'poster',
        width: 2000,
        height: 3000,
        aspectRatio: 0.667,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//5nEuAhCKrzf7bpGLBOal4qCuZsI.jpg',
        type: 'poster',
        width: 2000,
        height: 3000,
        aspectRatio: 0.667,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//ycDUaQMFEneD7ZoPTqhKbQd9JTG.jpg',
        type: 'poster',
        width: 1000,
        height: 1500,
        aspectRatio: 0.667,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//9yu8XNq18quSA9vp909CQRo4ksB.jpg',
        type: 'poster',
        width: 2000,
        height: 3000,
        aspectRatio: 0.667,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//xXLtaSj7UkNoabUhHIviC2BHDiA.jpg',
        type: 'poster',
        width: 2000,
        height: 3000,
        aspectRatio: 0.667,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//dWT4paigOO3oYjSGkjY9xMx2hBs.jpg',
        type: 'poster',
        width: 1000,
        height: 1500,
        aspectRatio: 0.667,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//dfZ4Zuo6D6ZsbOhT2mib4bXtCRR.jpg',
        type: 'poster',
        width: 2000,
        height: 2962,
        aspectRatio: 0.675,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//bWWciblTuuKXDkSrTXRV5aseLZy.jpg',
        type: 'poster',
        width: 1600,
        height: 2400,
        aspectRatio: 0.667,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//hECAnY1yKcmdfIYovaxFLUd2R0d.jpg',
        type: 'poster',
        width: 1000,
        height: 1500,
        aspectRatio: 0.667,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//kTMYjS6EkrTwugLtUYONIRX7UiL.jpg',
        type: 'poster',
        width: 1800,
        height: 2700,
        aspectRatio: 0.667,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//6u2xglqJqWAsg706sB7kosA9vMv.jpg',
        type: 'poster',
        width: 1000,
        height: 1500,
        aspectRatio: 0.667,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//JCo4gelTpavJin6CnzEdfYwLsM.jpg',
        type: 'poster',
        width: 1688,
        height: 2500,
        aspectRatio: 0.675,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//nLA4VD1Q6ZvpgCxIMwoHVwW6yaC.jpg',
        type: 'poster',
        width: 876,
        height: 1280,
        aspectRatio: 0.684,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//voT4YNKI3zQZVrUVmjXFfjvR0Vk.jpg',
        type: 'poster',
        width: 1285,
        height: 1927,
        aspectRatio: 0.667,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//fpwAkeawcsUWPl34Gomy1SajOTw.jpg',
        type: 'poster',
        width: 2000,
        height: 3000,
        aspectRatio: 0.667,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//6B5sAZ8ZM9OfDBpCXFUNeZ66K5W.jpg',
        type: 'poster',
        width: 852,
        height: 1278,
        aspectRatio: 0.667,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//gBKY10ioYBwlkZcsV6FDLOo5Cnk.jpg',
        type: 'poster',
        width: 2000,
        height: 3000,
        aspectRatio: 0.667,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//iNnJXQsMpndGZV2PxJD7eMrz931.jpg',
        type: 'poster',
        width: 2000,
        height: 3000,
        aspectRatio: 0.667,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//BAuj5e4pqMbLGVOci7B9abEto5.jpg',
        type: 'poster',
        width: 1000,
        height: 1500,
        aspectRatio: 0.667,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//vx7uXkOMan4IWPW4WUao39nh0Bw.jpg',
        type: 'poster',
        width: 1000,
        height: 1500,
        aspectRatio: 0.667,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//4JilmCOkVm0Wf4WBjsPFLBfqI4.jpg',
        type: 'poster',
        width: 854,
        height: 1280,
        aspectRatio: 0.667,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//4ntcKuzX18beXeWmsLNG3kRPQwW.jpg',
        type: 'poster',
        width: 1000,
        height: 1500,
        aspectRatio: 0.667,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//fx6DkPz5tu4nqzFNT838VzJBPG1.jpg',
        type: 'poster',
        width: 852,
        height: 1278,
        aspectRatio: 0.667,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//cSUFuITYSoilm4pZyXVI4bzHnJ3.jpg',
        type: 'poster',
        width: 1800,
        height: 2700,
        aspectRatio: 0.667,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//vrdQC89HQxHKkmABvGxZzKEXXBd.jpg',
        type: 'poster',
        width: 853,
        height: 1280,
        aspectRatio: 0.666,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//4YQaKcfH9ytGfgDG8hLqjMphvyu.jpg',
        type: 'poster',
        width: 1704,
        height: 2560,
        aspectRatio: 0.666,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//qNTPU7se2RoosTyN9GcQSE1HMC0.jpg',
        type: 'poster',
        width: 864,
        height: 1280,
        aspectRatio: 0.675,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//K9XW5aU1vlqJ5ViFv282EMJpjD.jpg',
        type: 'poster',
        width: 2000,
        height: 2962,
        aspectRatio: 0.675,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//7CwHfBd5zsC3QOAtQBUt3KHIIvF.jpg',
        type: 'poster',
        width: 720,
        height: 1080,
        aspectRatio: 0.667,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//eN9bGsFPOffRIDPNYjzIMHxCtQQ.jpg',
        type: 'poster',
        width: 854,
        height: 1280,
        aspectRatio: 0.667,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//4B1g6VkbJi3QGiZlt8Qol96kLSx.jpg',
        type: 'poster',
        width: 854,
        height: 1280,
        aspectRatio: 0.667,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//ag5CV8TwoCfN39Tz4MVQz7tHfQX.jpg',
        type: 'poster',
        width: 854,
        height: 1280,
        aspectRatio: 0.667,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//9YnfpGWUmNrJ3sGDQZ3POuNC7DK.jpg',
        type: 'poster',
        width: 854,
        height: 1280,
        aspectRatio: 0.667,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//inOHMbXuwD8ywXa9DOy8YUFCzsv.jpg',
        type: 'poster',
        width: 839,
        height: 1236,
        aspectRatio: 0.679,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//bnaf1FBjiUP0BE07lYjOBVylLge.jpg',
        type: 'poster',
        width: 839,
        height: 1236,
        aspectRatio: 0.679,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//xh3gGOEv5Vt0Jlkf1SpZDlWmxtr.jpg',
        type: 'poster',
        width: 800,
        height: 1200,
        aspectRatio: 0.667,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//hF45Kju0el0e0Wc3DT8dBZU1eD3.jpg',
        type: 'poster',
        width: 1000,
        height: 1426,
        aspectRatio: 0.701,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//pCrsiCTipW7y37nAOa40J9QCywX.jpg',
        type: 'poster',
        width: 2000,
        height: 2962,
        aspectRatio: 0.675,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//GrYZxwXGtCdEDQlJXgRe16nCV5.jpg',
        type: 'poster',
        width: 1036,
        height: 1524,
        aspectRatio: 0.68,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//3EhxHFQIZygJT1l4KFpVJ7GIcsg.jpg',
        type: 'poster',
        width: 1382,
        height: 2047,
        aspectRatio: 0.675,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//5OkJuWHKV8Oezs3ZzSHpOVoKKgV.jpg',
        type: 'poster',
        width: 864,
        height: 1280,
        aspectRatio: 0.675,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//1Ej1rwobKPUgofK49Q3rZrGH28E.jpg',
        type: 'poster',
        width: 2000,
        height: 2999,
        aspectRatio: 0.667,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//xdD6UGMosXhY2DI630l2pZsCZYR.jpg',
        type: 'poster',
        width: 1012,
        height: 1350,
        aspectRatio: 0.75,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//f0iZdfaOr5rEBA5FTvjPBmYF9x6.jpg',
        type: 'poster',
        width: 1080,
        height: 1620,
        aspectRatio: 0.667,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//fi0BbH4QEiJlbGnNFVxzFxsR2BA.jpg',
        type: 'poster',
        width: 864,
        height: 1280,
        aspectRatio: 0.675,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//a4T4oeH2xNV7BpckgSUEzZlToJ1.jpg',
        type: 'poster',
        width: 770,
        height: 1100,
        aspectRatio: 0.7,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//vyvkoK2yBL6ihIrnblg0dC3NPRa.jpg',
        type: 'poster',
        width: 864,
        height: 1280,
        aspectRatio: 0.675,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//adQsbsqSUYiIrI8V40Kyupb62Fl.jpg',
        type: 'poster',
        width: 1944,
        height: 2880,
        aspectRatio: 0.675,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//i4jicpe2s5AZp94QiBRpO2g9Q2T.jpg',
        type: 'poster',
        width: 854,
        height: 1280,
        aspectRatio: 0.667,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//Ao9NbKPlfpmWp87x9lAZZCr1ey5.jpg',
        type: 'poster',
        width: 777,
        height: 1100,
        aspectRatio: 0.706,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//o7apz40pa5j0qKs9IRuFp9VLrO2.jpg',
        type: 'poster',
        width: 1000,
        height: 1500,
        aspectRatio: 0.667,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//xZmHkFH3fcO26971jQgMonp1AM4.jpg',
        type: 'poster',
        width: 500,
        height: 750,
        aspectRatio: 0.667,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//eEE1NXwBdSzLYbCBKQJnGXhTZ3I.jpg',
        type: 'poster',
        width: 2000,
        height: 3000,
        aspectRatio: 0.667,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//cuymrPD2LYGGFxSi8sYq4VDubiy.jpg',
        type: 'poster',
        width: 1152,
        height: 1729,
        aspectRatio: 0.666,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//s6kWi12bGWR03A7YHDzbgT1kIXo.jpg',
        type: 'poster',
        width: 720,
        height: 1080,
        aspectRatio: 0.667,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//rVYQmoSJwZUf7CBLpseeOOH2XQq.jpg',
        type: 'poster',
        width: 720,
        height: 1080,
        aspectRatio: 0.667,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//dw0ZOg7kUvd0lX9M3bkmFQdnuEO.jpg',
        type: 'poster',
        width: 720,
        height: 1080,
        aspectRatio: 0.667,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//oIWPI4OG9ILnRDlkc341xb9Hl2R.jpg',
        type: 'poster',
        width: 1705,
        height: 2560,
        aspectRatio: 0.666,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//97sAeLunFJBeVcFhynqvWdFcRFA.jpg',
        type: 'poster',
        width: 600,
        height: 900,
        aspectRatio: 0.667,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//w6SWR0K2ICgF8V9K1dg9pd1SXW6.jpg',
        type: 'poster',
        width: 743,
        height: 1100,
        aspectRatio: 0.675,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//56gvUkQj1eKHX3hzkVxdWKu8tq4.jpg',
        type: 'poster',
        width: 1025,
        height: 1538,
        aspectRatio: 0.666,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//fK9vnvAf5THQ8dnnuiGQbl34dB.jpg',
        type: 'poster',
        width: 1000,
        height: 1500,
        aspectRatio: 0.667,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//eDi7ENAFTFw2wdYYMM9q4H9bJQb.jpg',
        type: 'poster',
        width: 2000,
        height: 3000,
        aspectRatio: 0.667,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//fQ7WPSAJrPpiAbq3LV5VhApSjO.jpg',
        type: 'poster',
        width: 1000,
        height: 1500,
        aspectRatio: 0.667,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//jvjGu8LzHkqBqe4xdVtlDc12Jsq.jpg',
        type: 'poster',
        width: 2000,
        height: 3000,
        aspectRatio: 0.667,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//lvEllz3GInKSKAoR5YfrpMA1rqo.jpg',
        type: 'poster',
        width: 864,
        height: 1280,
        aspectRatio: 0.675,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//3q6DAYcUm2Qyui65IP7DrBKjUYz.jpg',
        type: 'poster',
        width: 1000,
        height: 1500,
        aspectRatio: 0.667,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//cpyvHkkeDLE99xgcrXny7TS7RUV.jpg',
        type: 'poster',
        width: 1000,
        height: 1500,
        aspectRatio: 0.667,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//gnvrYeN2w12JJuAvPqzlyDFQqY2.jpg',
        type: 'poster',
        width: 1280,
        height: 1920,
        aspectRatio: 0.667,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//22HgH5i5w74RKzkiJAEolACq8zJ.jpg',
        type: 'poster',
        width: 2000,
        height: 3000,
        aspectRatio: 0.667,
        isDefault: false,
        language: 'en',
      },
    ],
    videos: [
      {
        isDefault: false,
        language: 'en',
        name: 'Behind the Magic: The Visual Effects of Marvel Studios’ Doctor Strange in the Multiverse of Madness',
        official: true,
        publishedAt: '2022-09-02T16:20:48.000Z',
        quality: 1080,
        site: 'YouTube',
        type: 'Behind the Scenes',
        url: 'https://www.youtube.com/embed/7GQjuLqVabM',
      },
      {
        isDefault: false,
        language: 'en',
        name: 'Behind the Scenes: The MANY Doctor Strange Looks in Multiverse of Madness!',
        official: true,
        publishedAt: '2022-06-25T17:30:03.000Z',
        quality: 1080,
        site: 'YouTube',
        type: 'Featurette',
        url: 'https://www.youtube.com/embed/JAnPg9t5hw0',
      },
      {
        isDefault: false,
        language: 'en',
        name: 'Strange or Not Strange',
        official: true,
        publishedAt: '2022-06-21T17:30:07.000Z',
        quality: 1080,
        site: 'YouTube',
        type: 'Featurette',
        url: 'https://www.youtube.com/embed/cJny6hBdUXU',
      },
      {
        isDefault: false,
        language: 'en',
        name: 'Disney+ Announcement',
        official: true,
        publishedAt: '2022-06-02T16:00:38.000Z',
        quality: 1080,
        site: 'YouTube',
        type: 'Featurette',
        url: 'https://www.youtube.com/embed/v-rHrkgVIsw',
      },
      {
        isDefault: false,
        language: 'en',
        name: 'Illuminati',
        official: true,
        publishedAt: '2022-05-28T17:00:32.000Z',
        quality: 1080,
        site: 'YouTube',
        type: 'Teaser',
        url: 'https://www.youtube.com/embed/ipA03zcKZXc',
      },
      {
        isDefault: false,
        language: 'en',
        name: 'Forever',
        official: true,
        publishedAt: '2022-05-21T17:00:19.000Z',
        quality: 1080,
        site: 'YouTube',
        type: 'Teaser',
        url: 'https://www.youtube.com/embed/l575-B5d3rI',
      },
      {
        isDefault: false,
        language: 'en',
        name: 'Witchcraft',
        official: true,
        publishedAt: '2022-05-20T15:00:12.000Z',
        quality: 1080,
        site: 'YouTube',
        type: 'Teaser',
        url: 'https://www.youtube.com/embed/DqbapqqhyyQ',
      },
      {
        isDefault: false,
        language: 'en',
        name: 'Phenomenon',
        official: true,
        publishedAt: '2022-05-19T16:00:34.000Z',
        quality: 1080,
        site: 'YouTube',
        type: 'Teaser',
        url: 'https://www.youtube.com/embed/nckUIRJVu7w',
      },
      {
        isDefault: false,
        language: 'en',
        name: 'Is the Multiverse Real?! | Ask Marvel',
        official: true,
        publishedAt: '2022-05-18T18:30:36.000Z',
        quality: 1080,
        site: 'YouTube',
        type: 'Featurette',
        url: 'https://www.youtube.com/embed/XUYDyumsVtY',
      },
      {
        isDefault: false,
        language: 'en',
        name: 'Shatter',
        official: true,
        publishedAt: '2022-05-17T16:00:24.000Z',
        quality: 1080,
        site: 'YouTube',
        type: 'Teaser',
        url: 'https://www.youtube.com/embed/oLS0bTNFTdg',
      },
      {
        isDefault: false,
        language: 'en',
        name: 'Epic',
        official: true,
        publishedAt: '2022-05-15T16:00:10.000Z',
        quality: 1080,
        site: 'YouTube',
        type: 'Teaser',
        url: 'https://www.youtube.com/embed/Q7eWNIJGuoc',
      },
      {
        isDefault: false,
        language: 'en',
        name: 'Thrill',
        official: true,
        publishedAt: '2022-05-13T16:00:05.000Z',
        quality: 1080,
        site: 'YouTube',
        type: 'Teaser',
        url: 'https://www.youtube.com/embed/6O8XCGq58YE',
      },
      {
        isDefault: false,
        language: 'en',
        name: 'The Importance of Being Benedict',
        official: true,
        publishedAt: '2022-05-12T15:00:11.000Z',
        quality: 1080,
        site: 'YouTub2022-09-21T20:16:07.411411531Z e',
        type: 'Featurette',
        url: 'https://www.youtube.com/embed/FgaHvAmq0rM',
      },
      {
        isDefault: false,
        language: 'en',
        name: 'Biggest Ride',
        official: true,
        publishedAt: '2022-05-11T18:00:25.000Z',
        quality: 1080,
        site: 'YouTube',
        type: 'Teaser',
        url: 'https://www.youtube.com/embed/f4ePx0FcG6U',
      },
      {
        isDefault: false,
        language: 'en',
        name: 'Exhilarating',
        official: true,
        publishedAt: '2022-05-09T15:29:39.000Z',
        quality: 1080,
        site: 'YouTube',
        type: 'Teaser',
        url: 'https://www.youtube.com/embed/3IhB-PFLBbg',
      },
      {
        isDefault: false,
        language: 'en',
        name: '#1 in the World',
        official: true,
        publishedAt: '2022-05-08T15:00:32.000Z',
        quality: 1080,
        site: 'YouTube',
        type: 'Teaser',
        url: 'https://www.youtube.com/embed/mz7P-mJN6Hk',
      },
      {
        isDefault: false,
        language: 'en',
        name: 'Mind-Flip',
        official: true,
        publishedAt: '2022-05-07T15:00:10.000Z',
        quality: 1080,
        site: 'YouTube',
        type: 'Teaser',
        url: 'https://www.youtube.com/embed/N2TW4cko1DM',
      },
      {
        isDefault: false,
        language: 'en',
        name: 'Wild Ride',
        official: true,
        publishedAt: '2022-05-06T16:00:36.000Z',
        quality: 1080,
        site: 'YouTube',
        type: 'Teaser',
        url: 'https://www.youtube.com/embed/th4VARsuGyw',
      },
      {
        isDefault: false,
        language: 'en',
        name: 'Now Playing',
        official: true,
        publishedAt: '2022-05-05T16:03:38.000Z',
        quality: 1080,
        site: 'YouTube',
        type: 'Teaser',
        url: 'https://www.youtube.com/embed/AonzPeXXqFk',
      },
      {
        isDefault: false,
        language: 'en',
        name: 'Final Trailer',
        official: true,
        publishedAt: '2022-05-05T03:09:23.000Z',
        quality: 1080,
        site: 'YouTube',
        type: 'Trailer',
        url: 'https://www.youtube.com/embed/Rf8LAYJSOL8',
      },
      {
        isDefault: false,
        language: 'en',
        name: 'Fun',
        official: true,
        publishedAt: '2022-05-02T16:30:09.000Z',
        quality: 1080,
        site: 'YouTube',
        type: 'Teaser',
        url: 'https://www.youtube.com/embed/iRPabXACKFI',
      },
      {
        isDefault: false,
        language: 'en',
        name: 'Change',
        official: true,
        publishedAt: '2022-05-01T16:30:03.000Z',
        quality: 1080,
        site: 'YouTube',
        type: 'Teaser',
        url: 'https://www.youtube.com/embed/__Gugj6R8F0',
      },
      {
        isDefault: false,
        language: 'en',
        name: 'Impossibility',
        official: true,
        publishedAt: '2022-04-30T15:00:31.000Z',
        quality: 1080,
        site: 'YouTube',
        type: 'Teaser',
        url: 'https://www.youtube.com/embed/cvQFAa6M2Lc',
      },
      {
        isDefault: false,
        language: 'en',
        name: 'Wanda Returns Featurette',
        official: true,
        publishedAt: '2022-04-29T16:00:15.000Z',
        quality: 1080,
        site: 'YouTube',
        type: 'Featurette',
        url: 'https://www.youtube.com/embed/Spe4q3Dr-5E',
      },
      {
        isDefault: false,
        language: 'en',
        name: 'Illuminati',
        official: true,
        publishedAt: '2022-04-29T15:00:25.000Z',
        quality: 1080,
        site: 'YouTube',
        type: 'Teaser',
        url: 'https://www.youtube.com/embed/Ne7y9_AbBsY',
      },
      {
        isDefault: false,
        language: 'en',
        name: 'Time',
        official: true,
        publishedAt: '2022-04-26T07:00:02.000Z',
        quality: 1080,
        site: 'YouTube',
        type: 'Teaser',
        url: 'https://www.youtube.com/embed/3mSMUZ_aC14',
      },
      {
        isDefault: false,
        language: 'en',
        name: 'A Mind-Bending Vision Featurette',
        official: true,
        publishedAt: '2022-04-22T19:00:01.000Z',
        quality: 1080,
        site: 'YouTube',
        type: 'Behind the Scenes',
        url: 'https://www.youtube.com/embed/064DIV0d890',
      },
      {
        isDefault: false,
        language: 'en',
        name: 'Experience',
        official: true,
        publishedAt: '2022-04-20T16:00:36.000Z',
        quality: 1080,
        site: 'YouTube',
        type: 'Teaser',
        url: 'https://www.youtube.com/embed/zpz1Ncgx1KQ',
      },
      {
        isDefault: false,
        language: 'en',
        name: 'Ready',
        official: true,
        publishedAt: '2022-04-18T16:00:10.000Z',
        quality: 1080,
        site: 'YouTube',
        type: 'Teaser',
        url: 'https://www.youtube.com/embed/UffVhIixpLA',
      },
      {
        isDefault: false,
        language: 'en',
        name: 'Reckoning',
        official: true,
        publishedAt: '2022-04-13T14:00:24.000Z',
        quality: 1080,
        site: 'YouTube',
        type: 'Teaser',
        url: 'https://www.youtube.com/embed/vfP-rsKVNKs',
      },
      {
        isDefault: false,
        language: 'en',
        name: 'Enter the Multiverse',
        official: true,
        publishedAt: '2022-04-11T19:00:05.000Z',
        quality: 1080,
        site: 'YouTube',
        type: 'Behind the Scenes',
        url: 'https://www.youtube.com/embed/Gq5gLlb-298',
      },
      {
        isDefault: false,
        language: 'en',
        name: 'Cinematic',
        official: true,
        publishedAt: '2022-04-10T21:00:29.000Z',
        quality: 1080,
        site: 'YouTube',
        type: 'Teaser',
        url: 'https://www.youtube.com/embed/qejbofWMgy8',
      },
      {
        isDefault: false,
        language: 'en',
        name: 'Get Tickets Now',
        official: true,
        publishedAt: '2022-04-06T15:00:02.000Z',
        quality: 1080,
        site: 'YouTube',
        type: 'Featurette',
        url: 'https://www.youtube.com/embed/2MdjoLwsokA',
      },
      {
        isDefault: false,
        language: 'en',
        name: 'Dream',
        official: true,
        publishedAt: '2022-04-06T14:00:15.000Z',
        quality: 1080,
        site: 'YouTube',
        type: 'Teaser',
        url: 'https://www.youtube.com/embed/NLTYw1s4e-8',
      },
      {
        isDefault: false,
        language: 'en',
        name: 'Fate',
        official: true,
        publishedAt: '2022-04-02T16:00:24.000Z',
        quality: 1080,
        site: 'YouTube',
        type: 'Teaser',
        url: 'https://www.youtube.com/embed/UNnKAk79wws',
      },
      {
        isDefault: false,
        language: 'en',
        name: 'Official Trailer',
        official: true,
        publishedAt: '2022-02-13T23:12:44.000Z',
        quality: 1080,
        site: 'YouTube',
        type: 'Trailer',
        url: 'https://www.youtube.com/embed/aWzlQ2N6qqg',
      },
      {
        isDefault: false,
        language: 'en',
        name: 'Official Teaser',
        official: true,
        publishedAt: '2021-12-22T16:02:16.000Z',
        quality: 1080,
        site: 'YouTube',
        type: 'Teaser',
        url: 'https://www.youtube.com/embed/Rt_UqUm38BI',
      },
    ],
    actors: [
      {
        name: 'Benedict Cumberbatch',
        image:
          'https://m.media-amazon.com/images/M/MV5BMjE0MDkzMDQwOF5BMl5BanBnXkFtZTgwOTE1Mjg1MzE@._V1_QL75_UX280_CR0,17,280,280_.jpg',
        role: 'Doctor Stephen Strange',
      },
      {
        name: 'Elizabeth Olsen',
        image:
          'https://m.media-amazon.com/images/M/MV5BMjEzMjA0ODk1OF5BMl5BanBnXkFtZTcwMTA4ODM3OQ@@._V1_QL75_UX280_CR0,11,280,280_.jpg',
        role: 'Wanda Maximoff',
      },
      {
        name: 'Chiwetel Ejiofor',
        image:
          'https://m.media-amazon.com/images/M/MV5BNzA5MDEyMTY3Nl5BMl5BanBnXkFtZTgwODQ0MjcxMDE@._V1_QL75_UX280_CR0,10,280,280_.jpg',
        role: 'Baron Mordo',
      },
      {
        name: 'Benedict Wong',
        image:
          'https://m.media-amazon.com/images/M/MV5BMDMxOGExNWItYjM4YS00ZDJhLWJiM2UtMTViYjhhNTM4OGYxXkEyXkFqcGdeQXVyMTgyMzY5MTk@._V1_QL75_UX280_CR0,1,280,280_.jpg',
        role: 'Wong',
      },
      {
        name: 'Xochitl Gomez',
        image:
          'https://m.media-amazon.com/images/M/MV5BOWM0NGFkYmQtYjM4My00YzQ0LWJjOWItM2VkNWE1Nzc3MTI4XkEyXkFqcGdeQXVyODU1ODI5NDA@._V1_QL75_UX280_CR0,37,280,280_.jpg',
        role: 'America Chavez',
      },
      {
        name: 'Rachel McAdams',
        image:
          'https://m.media-amazon.com/images/M/MV5BMTY5ODcxMDU4NV5BMl5BanBnXkFtZTcwMjAzNjQyNQ@@._V1_QL75_UX280_CR0,17,280,280_.jpg',
        role: 'Dr. Christine Palmer',
      },
      {
        name: 'Jett Klyne',
        image:
          'https://m.media-amazon.com/images/M/MV5BMDhkZGQ5OTMtODUyZS00MzY2LWEwNDUtZTY2NGViOWEzMjliXkEyXkFqcGdeQXVyNTg3OTIyNzc@._V1_QL75_UY280_CR70,0,280,280_.jpg',
        role: 'Tommy Maximoff',
      },
      {
        name: 'Julian Hilliard',
        image:
          'https://m.media-amazon.com/images/M/MV5BODFkZjJmMjctNzA2NC00M2Y2LThmMjEtYTJjMmM0NmQ2NzFjXkEyXkFqcGdeQXVyODA4MTYwMjc@._V1_QL75_UX280_CR0,10,280,280_.jpg',
        role: 'Billy Maximoff',
      },
      {
        name: 'Michael Stuhlbarg',
        image:
          'https://m.media-amazon.com/images/M/MV5BNjdjNTlhZjUtODA0MC00Mjc3LWExNmMtZDc5ZmI0ZmNlZWZmXkEyXkFqcGdeQXVyMjQwMDg0Ng@@._V1_QL75_UX280_CR0,24,280,280_.jpg',
        role: 'Dr. Nic West',
      },
      {
        name: 'Hayley Atwell',
        image:
          'https://m.media-amazon.com/images/M/MV5BZmRhZWVjZWMtMzUwZi00OTI3LThiMzAtY2VmMjU5YjQ0YjVjXkEyXkFqcGdeQXVyODMzMTM1MDc@._V1_QL75_UX280_CR0,0,280,280_.jpg',
        role: 'Captain Carter',
      },
      {
        name: 'Anson Mount',
        image:
          'https://m.media-amazon.com/images/M/MV5BNjk5ODY0NTkzMV5BMl5BanBnXkFtZTgwNjY3Mzc5NzE@._V1_QL75_UY280_CR70,0,280,280_.jpg',
        role: 'Black Bolt',
      },
      {
        name: 'Lashana Lynch',
        image:
          'https://m.media-amazon.com/images/M/MV5BMjI0ZGE0ZTYtYmY1MS00MGU0LWEwMDQtMzYxMDFmMmFjZjUyXkEyXkFqcGdeQXVyMzczOTY5ODk@._V1_QL75_UX280_CR0,0,280,280_.jpg',
        role: 'Captain Marvel',
      },
      {
        name: 'John Krasinski',
        image:
          'https://m.media-amazon.com/images/M/MV5BMTc3MzY3MjQ3OV5BMl5BanBnXkFtZTcwODI3NjQxMw@@._V1_QL75_UX280_CR0,9,280,280_.jpg',
        role: 'Reed Richards',
      },
      {
        name: 'Patrick Stewart',
        image:
          'https://m.media-amazon.com/images/M/MV5BMTc0MzU5ODQ5OF5BMl5BanBnXkFtZTYwODIwODk1._V1_QL75_UX280_CR0,13,280,280_.jpg',
        role: 'Professor Charles Xavier',
      },
      {
        name: 'Charlize Theron',
        image:
          'https://m.media-amazon.com/images/M/MV5BMTk5Mzc4ODU0Ml5BMl5BanBnXkFtZTcwNjU1NTI0Mw@@._V1_QL75_UX280_CR0,1,280,280_.jpg',
        role: 'Clea',
      },
      {
        name: 'Sheila Atim',
        image:
          'https://m.media-amazon.com/images/M/MV5BNWEwMWUwNzItNWQ1Yi00ZGZiLTllNTYtYmM5NjRhZDA3YzY2XkEyXkFqcGdeQXVyNzE5NDI1MTY@._V1_QL75_UX280_CR0,0,280,280_.jpg',
        role: 'Sara',
      },
      {
        name: 'Adam Hugill',
        image:
          'https://m.media-amazon.com/images/M/MV5BYjViNTFhNzQtMjdhYi00OTlmLTk0NzYtZGNkYzE2ZWYxZjcyXkEyXkFqcGdeQXVyMjQwMDg0Ng@@._V1_QL75_UX280_CR0,0,280,280_.jpg',
        role: 'Rintrah',
      },
      {
        name: 'Bruce Campbell',
        image:
          'https://m.media-amazon.com/images/M/MV5BOTY2MTg0OTEzOV5BMl5BanBnXkFtZTgwNzQ3NTcwMjE@._V1_QL75_UX280_CR0,24,280,280_.jpg',
        role: 'Pizza Poppa',
      },
    ],
    directors: [{ name: 'Sam Raimi', image: 'default.png' }],
    genres: [{ name: 'Action' }, { name: 'Adventure' }, { name: 'Fantasy' }],
    languages: [{ name: 'English' }, { name: 'Spanish' }, { name: 'Chinese' }],
    studios: [{ name: 'Marvel Studios', image: '' }],
    writers: [
      { name: 'Michael Waldron', image: 'default.png' },
      {
        name: 'Stan Lee',
        image: 'default.png',
      },
      { name: 'Steve Ditko', image: 'default.png' },
    ],
  },
};
