export default {
  loki: {
    show: {
      type: 'TV Series',
      name: 'Loki',
      releaseYear: null,
      length: 0,
      summary:
        'The mercurial villain Loki resumes his role as the God of Mischief in a new series that takes place after the events of “Avengers: Endgame.”',
      pgRating: '2021– ',
      series: {
        avgEpisodeLength: 0,
        type: 'TV Series',
        episodes: [
          {
            name: '',
            number: 1,
            season: 1,
            releaseDate: '',
            length: 0,
            summary: '',
            urls: [
              {
                serverName: 'membed',
                url: 'https://sbplay2.xyz/e/1k7vzpf14b2e?caption_1=https://msubload.com/sub/loki-season-1-episode-1-glorious-purpose/loki-season-1-episode-1-glorious-purpose.vtt&sub_1=English',
              },
            ],
          },
          {
            name: '',
            number: 2,
            season: 1,
            releaseDate: '',
            length: 0,
            summary: '',
            urls: [
              {
                serverName: 'membed',
                url: 'https://sbplay2.xyz/e/wlzktww3pitd?caption_1=https://msubload.com/sub/loki-season-1-episode-2/loki-season-1-episode-2.vtt&sub_1=English',
              },
            ],
          },
          {
            name: '',
            number: 3,
            season: 1,
            releaseDate: '',
            length: 0,
            summary: '',
            urls: [
              {
                serverName: 'membed',
                url: 'https://sbplay2.xyz/e/ae2ybhaq65wp?caption_1=https://msubload.com/sub/loki-season-1-episode-3-lamentis/loki-season-1-episode-3-lamentis.vtt&sub_1=English',
              },
            ],
          },
          {
            name: '',
            number: 4,
            season: 1,
            releaseDate: '',
            length: 0,
            summary: '',
            urls: [
              {
                serverName: 'membed',
                url: 'https://sbplay2.xyz/e/prwt2l5375pm?caption_1=https://msubload.com/sub/loki-season-1-episode-4-the-nexus-event/loki-season-1-episode-4-the-nexus-event.vtt&sub_1=English',
              },
            ],
          },
          {
            name: '',
            number: 5,
            season: 1,
            releaseDate: '',
            length: 0,
            summary: '',
            urls: [
              {
                serverName: 'membed',
                url: 'https://sbplay2.xyz/e/9816l6y68f5p?caption_1=https://msubload.com/sub/loki-season-1-episode-5/loki-season-1-episode-5.vtt&sub_1=English',
              },
            ],
          },
          {
            name: '',
            number: 1,
            season: 2,
            releaseDate: '',
            length: 0,
            summary: '',
            urls: [
              {
                serverName: 'membed',
                url: 'https://sbplay2.xyz/e/1k7vzpf14b2e?caption_1=https://msubload.com/sub/loki-season-1-episode-1-glorious-purpose/loki-season-1-episode-1-glorious-purpose.vtt&sub_1=English',
              },
            ],
          },
          {
            name: '',
            number: 2,
            season: 2,
            releaseDate: '',
            length: 0,
            summary: '',
            urls: [
              {
                serverName: 'membed',
                url: 'https://sbplay2.xyz/e/wlzktww3pitd?caption_1=https://msubload.com/sub/loki-season-1-episode-2/loki-season-1-episode-2.vtt&sub_1=English',
              },
            ],
          },
          {
            name: '',
            number: 3,
            season: 2,
            releaseDate: '',
            length: 0,
            summary: '',
            urls: [
              {
                serverName: 'membed',
                url: 'https://sbplay2.xyz/e/ae2ybhaq65wp?caption_1=https://msubload.com/sub/loki-season-1-episode-3-lamentis/loki-season-1-episode-3-lamentis.vtt&sub_1=English',
              },
            ],
          },
          {
            name: '',
            number: 4,
            season: 2,
            releaseDate: '',
            length: 0,
            summary: '',
            urls: [
              {
                serverName: 'membed',
                url: 'https://sbplay2.xyz/e/prwt2l5375pm?caption_1=https://msubload.com/sub/loki-season-1-episode-4-the-nexus-event/loki-season-1-episode-4-the-nexus-event.vtt&sub_1=English',
              },
            ],
          },
          {
            name: '',
            number: 5,
            season: 2,
            releaseDate: '',
            length: 0,
            summary: '',
            urls: [
              {
                serverName: 'membed',
                url: 'https://sbplay2.xyz/e/9816l6y68f5p?caption_1=https://msubload.com/sub/loki-season-1-episode-5/loki-season-1-episode-5.vtt&sub_1=English',
              },
            ],
          },
        ],
      },
    },
    servers: [{ name: 'membed', url: 'https://membed.net/encrypt-ajax.php' }],
    imdb: { imdbId: 'tt9140554', rating: 8.2, voteCount: 305000 },
    images: [
      {
        url: 'https://m.media-amazon.com/images/M/MV5BNTkwOTE1ZDYtODQ3Yy00YTYwLTg0YWQtYmVkNmFjNGZlYmRiXkEyXkFqcGdeQXVyNTc4MjczMTM@._V1_QL75_UX380_CR0,0,380,562_.jpg',
        type: 'poster',
        width: null,
        height: null,
        aspectRatio: null,
        isDefault: true,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//bZGAX8oMDm3Mo5i0ZPKh9G2OcaO.jpg',
        type: 'backdrop',
        width: 2880,
        height: 1620,
        aspectRatio: 1.778,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//anp5ubvD7frvXMZMaMuxeFRhfWm.jpg',
        type: 'backdrop',
        width: 1920,
        height: 1080,
        aspectRatio: 1.778,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//xxlteGxXhpgnoMF7SvdYwHvljnB.jpg',
        type: 'backdrop',
        width: 2160,
        height: 1215,
        aspectRatio: 1.778,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//f5tjVQtxihaVwXOdpITSPeIqlpX.jpg',
        type: 'backdrop',
        width: 1920,
        height: 1080,
        aspectRatio: 1.778,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//jOJP93WpQrmSXX16lQCNulwuUVO.jpg',
        type: 'backdrop',
        width: 1920,
        height: 1080,
        aspectRatio: 1.778,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//gB1sop3Z0M5xtG0otDfDJLSdq1a.jpg',
        type: 'backdrop',
        width: 1920,
        height: 1080,
        aspectRatio: 1.778,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//sVEfpGeG3Vbv2H4xQKmN2Oc2jBo.jpg',
        type: 'backdrop',
        width: 1920,
        height: 1080,
        aspectRatio: 1.778,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//nvvCUzCgLY2ScgfckitjxBzn4sA.jpg',
        type: 'backdrop',
        width: 1920,
        height: 1080,
        aspectRatio: 1.778,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//qUKNqCrD9qcEp7QNXbusPPtavE5.jpg',
        type: 'backdrop',
        width: 1920,
        height: 1080,
        aspectRatio: 1.778,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//tJPM9kRFnMlHoOx4AEnw3Ju2oBv.jpg',
        type: 'backdrop',
        width: 1920,
        height: 1080,
        aspectRatio: 1.778,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//DMrInV58amYzCZaqkcJn73q9ky.jpg',
        type: 'backdrop',
        width: 1920,
        height: 1080,
        aspectRatio: 1.778,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//8iy6aBswkcSobgybB0h6a9ctoHG.jpg',
        type: 'backdrop',
        width: 1920,
        height: 1080,
        aspectRatio: 1.778,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//1WU7SMZtcfMwoGjM5UcdHxwkQev.jpg',
        type: 'backdrop',
        width: 1920,
        height: 1080,
        aspectRatio: 1.778,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//71kjcn5PYnNz3bMOZnGyuR4RH1V.jpg',
        type: 'backdrop',
        width: 3840,
        height: 2160,
        aspectRatio: 1.778,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//Afp8OhiO0Ajb3NPoCBvfu2pqaeO.jpg',
        type: 'backdrop',
        width: 2364,
        height: 1330,
        aspectRatio: 1.777,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//7jE9RYxuFNGz5Lw0UVGXV7jZ7y8.jpg',
        type: 'backdrop',
        width: 3840,
        height: 2160,
        aspectRatio: 1.778,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//vttOoJ9aGKHY05Gsb1lNbOAZgTM.jpg',
        type: 'backdrop',
        width: 2160,
        height: 1215,
        aspectRatio: 1.778,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//wr7nrzDrpGCEgYnw15jyAB59PtZ.jpg',
        type: 'backdrop',
        width: 1920,
        height: 1080,
        aspectRatio: 1.778,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//ykElAtsOBoArgI1A8ATVH0MNve0.jpg',
        type: 'backdrop',
        width: 3840,
        height: 2160,
        aspectRatio: 1.778,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//rSumVltOLWsmsK5wqWIDZEFGL2H.jpg',
        type: 'backdrop',
        width: 3840,
        height: 2160,
        aspectRatio: 1.778,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//nCaL5Yd7VXn0yI3HmjtG0DL9NKo.jpg',
        type: 'backdrop',
        width: 1280,
        height: 720,
        aspectRatio: 1.778,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//kXja7L9cRlsRmINMpxyWEdp9r3u.jpg',
        type: 'backdrop',
        width: 3840,
        height: 2160,
        aspectRatio: 1.778,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//gpaBuaGuQqkHeAbkS6XnE0zGUrj.jpg',
        type: 'backdrop',
        width: 3840,
        height: 2160,
        aspectRatio: 1.778,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//sE9F4FS7opmWl2ingcinEW7oacM.jpg',
        type: 'backdrop',
        width: 1280,
        height: 720,
        aspectRatio: 1.778,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//kUAGU6YnhXjw7kdPEibyVM8ff3q.jpg',
        type: 'backdrop',
        width: 1280,
        height: 720,
        aspectRatio: 1.778,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//4ziFuhVV5tTu6MOC7tKMOf31enC.jpg',
        type: 'backdrop',
        width: 1280,
        height: 720,
        aspectRatio: 1.778,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//umF6NuIJguZpsNqp4sfLGr8qfvK.jpg',
        type: 'backdrop',
        width: 1280,
        height: 720,
        aspectRatio: 1.778,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//mTZCyABVMhbujrzkrLo7PpJ4xO1.jpg',
        type: 'backdrop',
        width: 1280,
        height: 720,
        aspectRatio: 1.778,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//sMeF4YGAzHNiEUTxlit5oseD8CA.jpg',
        type: 'backdrop',
        width: 3840,
        height: 2160,
        aspectRatio: 1.778,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//4AaWduGXcMrHYPlroq9N98vaid1.jpg',
        type: 'backdrop',
        width: 2835,
        height: 1595,
        aspectRatio: 1.777,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//36CTFM2xq3qpfaHVh960McO0etL.jpg',
        type: 'backdrop',
        width: 3840,
        height: 2160,
        aspectRatio: 1.778,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//rsXvPMXywgPPiylJHVL1q29x7J6.jpg',
        type: 'backdrop',
        width: 1920,
        height: 1080,
        aspectRatio: 1.778,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//6yb7XUr6l7ctCwf8OJ9NN5brQ53.png',
        type: 'logo',
        width: 3145,
        height: 917,
        aspectRatio: 3.43,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//zzjG9U2fDOiHudgqUysbKW58hLp.png',
        type: 'logo',
        width: 3145,
        height: 1298,
        aspectRatio: 2.423,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//qUy338DwcJWLPZogPUhiEcVJXe3.png',
        type: 'logo',
        width: 3145,
        height: 1298,
        aspectRatio: 2.423,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//eNnlAd0jT01P0gLULcERCsfcAOY.png',
        type: 'logo',
        width: 1206,
        height: 676,
        aspectRatio: 1.784,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//kEl2t3OhXc3Zb9FBh1AuYzRTgZp.jpg',
        type: 'poster',
        width: 2000,
        height: 3000,
        aspectRatio: 0.667,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//rX1wQMTKFqF0gvZyS0DDQqgnQPB.jpg',
        type: 'poster',
        width: 2000,
        height: 3000,
        aspectRatio: 0.667,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//3oo3ahDy3ibRkZp9CTytqZ8Ajta.jpg',
        type: 'poster',
        width: 1000,
        height: 1500,
        aspectRatio: 0.667,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//lch4lTR1gZxXp3L8wzaBM86v4Zi.jpg',
        type: 'poster',
        width: 2000,
        height: 3000,
        aspectRatio: 0.667,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//fKDtP8ru6h6iwzLZz2dgrCuEhFM.jpg',
        type: 'poster',
        width: 1000,
        height: 1500,
        aspectRatio: 0.667,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//2FEa5NEFwgotzRPZRPG8lRSmJp5.jpg',
        type: 'poster',
        width: 1666,
        height: 2500,
        aspectRatio: 0.666,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//4vgCMvixSxYJ4CVzQXLnR0bsA8y.jpg',
        type: 'poster',
        width: 1666,
        height: 2500,
        aspectRatio: 0.666,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//dWTkOWjvVSeVD7nCMrfKTDikLUK.jpg',
        type: 'poster',
        width: 1666,
        height: 2500,
        aspectRatio: 0.666,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//xN7ikdY5Vg3HLYfeVstY9OBJCfK.jpg',
        type: 'poster',
        width: 1666,
        height: 2500,
        aspectRatio: 0.666,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//hZd6Z2e5Epb2xoEFKm3cv7hgiKv.jpg',
        type: 'poster',
        width: 1666,
        height: 2500,
        aspectRatio: 0.666,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//epQKuwbgiLstj7v0TPLHWB6bkmT.jpg',
        type: 'poster',
        width: 1688,
        height: 2500,
        aspectRatio: 0.675,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//Qa6p6GdfnpfayZMqFbbDPMEaw7.jpg',
        type: 'poster',
        width: 1688,
        height: 2500,
        aspectRatio: 0.675,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//fnz07b7pyt7OZxfHanoKTHT9ldO.jpg',
        type: 'poster',
        width: 1688,
        height: 2500,
        aspectRatio: 0.675,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//A5lALywEh7Iwnyc53IwAV6t7aOe.jpg',
        type: 'poster',
        width: 1688,
        height: 2500,
        aspectRatio: 0.675,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//5QjRRtT3zvDIBqfr0BrYbyPwpQ1.jpg',
        type: 'poster',
        width: 1688,
        height: 2500,
        aspectRatio: 0.675,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//ryjHVu68Hgk368sS8KpdzHapx3J.jpg',
        type: 'poster',
        width: 1687,
        height: 2500,
        aspectRatio: 0.675,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//oQ5JQbu2gzkevpR3wrSfH9mp8HU.jpg',
        type: 'poster',
        width: 1000,
        height: 1500,
        aspectRatio: 0.667,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//dqqV9MrRa7O19aiGWCKYFeedY0A.jpg',
        type: 'poster',
        width: 1000,
        height: 1500,
        aspectRatio: 0.667,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//42zn3rSebfuWh4XFuoOML25FXgg.jpg',
        type: 'poster',
        width: 1666,
        height: 2500,
        aspectRatio: 0.666,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//nL8CkITckZPG294BYszAE1DTlTO.jpg',
        type: 'poster',
        width: 1688,
        height: 2500,
        aspectRatio: 0.675,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//x8nGjiBTZKpWbK9SONXxWo8YiWq.jpg',
        type: 'poster',
        width: 1666,
        height: 2500,
        aspectRatio: 0.666,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//7V8e5IqVTutgWlrUVS8lllILARy.jpg',
        type: 'poster',
        width: 1666,
        height: 2500,
        aspectRatio: 0.666,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//gJBqHWDKLKdPhd011bcGgQTT9Ib.jpg',
        type: 'poster',
        width: 1000,
        height: 1500,
        aspectRatio: 0.667,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//1ggA8LZLrnMzkCrpMDuJKfAO8vZ.jpg',
        type: 'poster',
        width: 1667,
        height: 2500,
        aspectRatio: 0.667,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//5wdiaIThjD1Rt6eGtL8f8qczqTY.jpg',
        type: 'poster',
        width: 1666,
        height: 2500,
        aspectRatio: 0.666,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//uK6QrIcvwYEL5Vx94S2uUcD2ocM.jpg',
        type: 'poster',
        width: 1687,
        height: 2500,
        aspectRatio: 0.675,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//2F7OsqC6M6oNeewQBF9xyymJ4zz.jpg',
        type: 'poster',
        width: 2000,
        height: 3000,
        aspectRatio: 0.667,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//kC6jPCUBrOKAKj261lyXyTBjMmM.jpg',
        type: 'poster',
        width: 2000,
        height: 3000,
        aspectRatio: 0.667,
        isDefault: false,
        language: null,
      },
      {
        url: 'https://api.themoviedb.org/3//original//i34yJ0AVKbRYZ9rQhcDDfml5Ed4.jpg',
        type: 'poster',
        width: 839,
        height: 1236,
        aspectRatio: 0.679,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//hLXukcRkTxwmZCzSdmhFIAQlWQu.jpg',
        type: 'poster',
        width: 1000,
        height: 1500,
        aspectRatio: 0.667,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//jmuKWb3MvZVCsNujENV8vGfyR6F.jpg',
        type: 'poster',
        width: 1666,
        height: 2500,
        aspectRatio: 0.666,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//uc7ahCgqIVtasfYaqCVGHA3R8Xd.jpg',
        type: 'poster',
        width: 1000,
        height: 1500,
        aspectRatio: 0.667,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//7OlSwuSare8whfXWArTHsZdgejJ.jpg',
        type: 'poster',
        width: 864,
        height: 1280,
        aspectRatio: 0.675,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//bauYNAukhN7QH9FNh6j2Zg12htL.jpg',
        type: 'poster',
        width: 1000,
        height: 1500,
        aspectRatio: 0.667,
        isDefault: false,
        language: 'en',
      },
      {
        url: 'https://api.themoviedb.org/3//original//lBynNY1DlQiJ1lZTteEBtX84s9b.jpg',
        type: 'poster',
        width: 2000,
        height: 3000,
        aspectRatio: 0.667,
        isDefault: false,
        language: 'en',
      },
    ],
    videos: [
      {
        isDefault: false,
        language: 'en',
        name: 'Help',
        official: true,
        publishedAt: '2021-06-08T16:00:06.000Z',
        quality: 1080,
        site: 'You2022-09-22T09:06:06.098201645Z Tube',
        type: 'Teaser',
        url: 'https://www.youtube.com/embed/R6o1UWEBVQA',
      },
      {
        isDefault: false,
        language: 'en',
        name: 'Escape',
        official: true,
        publishedAt: '2021-06-07T18:00:17.000Z',
        quality: 1080,
        site: 'YouTube',
        type: 'Teaser',
        url: 'https://www.youtube.com/embed/TGT8phM-cK0',
      },
      {
        isDefault: false,
        language: 'en',
        name: 'Owen Wilson Joins the MCU Featurette',
        official: true,
        publishedAt: '2021-06-07T15:00:22.000Z',
        quality: 1080,
        site: 'YouTube',
        type: 'Featurette',
        url: 'https://www.youtube.com/embed/7y4-WSywiSY',
      },
      {
        isDefault: false,
        language: 'en',
        name: 'Team',
        official: true,
        publishedAt: '2021-06-05T18:00:02.000Z',
        quality: 1080,
        site: 'YouTube',
        type: 'Teaser',
        url: 'https://www.youtube.com/embed/9ISqTQ_cBNY',
      },
      {
        isDefault: false,
        language: 'en',
        name: 'Chance',
        official: true,
        publishedAt: '2021-06-05T01:27:00.000Z',
        quality: 1080,
        site: 'YouTube',
        type: 'Teaser',
        url: 'https://www.youtube.com/embed/CnSNmt7e1YA',
      },
      {
        isDefault: false,
        language: 'en',
        name: 'Tick',
        official: true,
        publishedAt: '2021-06-03T21:45:01.000Z',
        quality: 1080,
        site: 'YouTube',
        type: 'Teaser',
        url: 'https://www.youtube.com/embed/GZe1P6Hg0cc',
      },
      {
        isDefault: false,
        language: 'en',
        name: 'Mischief Featurette',
        official: true,
        publishedAt: '2021-06-02T14:01:19.000Z',
        quality: 1080,
        site: 'YouTube',
        type: 'Featurette',
        url: 'https://www.youtube.com/embed/1-xfM_COCmY',
      },
      {
        isDefault: false,
        language: 'en',
        name: 'Chaos',
        official: true,
        publishedAt: '2021-05-27T17:00:02.000Z',
        quality: 1080,
        site: 'YouTube',
        type: 'Teaser',
        url: 'https://www.youtube.com/embed/FgKNTA_CvO4',
      },
      {
        isDefault: false,
        language: 'en',
        name: 'Clock',
        official: true,
        publishedAt: '2021-05-23T16:00:19.000Z',
        quality: 1080,
        site: 'YouTube',
        type: 'Teaser',
        url: 'https://www.youtube.com/embed/s0nTq-NUvU4',
      },
      {
        isDefault: false,
        language: 'en',
        name: 'Loki in 30 Seconds Featurette',
        official: true,
        publishedAt: '2021-05-20T19:00:02.000Z',
        quality: 1080,
        site: 'YouTube',
        type: 'Featurette',
        url: 'https://www.youtube.com/embed/7LydHN2_eE4',
      },
      {
        isDefault: false,
        language: 'en',
        name: 'Miss Minutes',
        official: true,
        publishedAt: '2021-05-19T14:00:04.000Z',
        quality: 1080,
        site: 'YouTube',
        type: 'Teaser',
        url: 'https://www.youtube.com/embed/5vpCIadly88',
      },
      {
        isDefault: false,
        language: 'en',
        name: 'Doing Great',
        official: true,
        publishedAt: '2021-05-05T19:00:03.000Z',
        quality: 1080,
        site: 'YouTube',
        type: 'Teaser',
        url: 'https://www.youtube.com/embed/EVvK10eFmo8',
      },
      {
        isDefault: false,
        language: 'en',
        name: 'Announcement',
        official: true,
        publishedAt: '2021-05-05T16:00:38.000Z',
        quality: 1080,
        site: 'YouTube',
        type: 'Teaser',
        url: 'https://www.youtube.com/embed/mNyLzc3MU_E',
      },
      {
        isDefault: false,
        language: 'en',
        name: 'Official Trailer',
        official: true,
        publishedAt: '2021-04-05T13:00:01.000Z',
        quality: 1080,
        site: 'YouTube',
        type: 'Trailer',
        url: 'https://www.youtube.com/embed/nW948Va-l10',
      },
      {
        isDefault: false,
        language: 'en',
        name: 'Exclusive Clip',
        official: true,
        publishedAt: '2020-12-11T00:46:34.000Z',
        quality: 1080,
        site: 'YouTube',
        type: 'Trailer',
        url: 'https://www.youtube.com/embed/G4JuopziR3Q',
      },
    ],
    actors: [
      {
        name: 'Tom Hiddleston12 episodes12 eps • 2021–2023',
        image:
          'https://m.media-amazon.com/images/M/MV5BNWYwODAyZjAtOTQ1My00MDY2LTg0NDQtZGFiMDRiYzY4ZmM2XkEyXkFqcGdeQXVyNjg2NjQwMDQ@._V1_QL75_UX280_CR0,4,280,280_.jpg',
        role: 'Loki',
      },
      {
        name: 'Owen Wilson5 episodes5 eps • 2021',
        image:
          'https://m.media-amazon.com/images/M/MV5BMTgwMzQ4ODYxMV5BMl5BanBnXkFtZTcwNDAwMTc2NQ@@._V1_QL75_UX280_CR0,37,280,280_.jpg',
        role: 'Mobius',
      },
      {
        name: 'Eugene Cordero9 episodes9 eps • 2021–2023',
        image:
          'https://m.media-amazon.com/images/M/MV5BMTgzMzM4NDc3MV5BMl5BanBnXkFtZTcwNjc1MTk1OQ@@._V1_QL75_UX280_CR0,25,280,280_.jpg',
        role: 'Casey',
      },
      {
        name: 'Gugu Mbatha-Raw6 episodes6 eps • 2021',
        image:
          'https://m.media-amazon.com/images/M/MV5BM2FlZWVlYWMtMDM5OC00M2IxLWI5ZmYtNzdiNGQ1OTA0MjgzXkEyXkFqcGdeQXVyOTIzNjQ2NjY@._V1_QL75_UX280_CR0,0,280,280_.jpg',
        role: 'Ravonna Renslayer',
      },
      {
        name: 'Ke Huy Quan6 episodes6 eps • 2023',
        image:
          'https://m.media-amazon.com/images/M/MV5BMmMyN2MxMjQtNDFjYi00MTE3LTgwYTMtZmQzODUyZGUwYmExXkEyXkFqcGdeQXVyMTM5NDUxMTA@._V1_QL75_UX280_CR0,24,280,280_.jpg',
        role: '',
      },
      {
        name: 'Sophia Di Martino5 episodes5 eps • 2021',
        image:
          'https://m.media-amazon.com/images/M/MV5BYjk4YmMyOWYtMzlhZS00Yjg4LTk0NjQtNDdmMmViMzk3MDZhXkEyXkFqcGdeQXVyMjQwMDg0Ng@@._V1_QL75_UX280_CR0,24,280,280_.jpg',
        role: 'Sylvie',
      },
      {
        name: 'Wunmi Mosaku5 episodes5 eps • 2021',
        image:
          'https://m.media-amazon.com/images/M/MV5BMTA4ODkxOTEwMzZeQTJeQWpwZ15BbWU4MDc4NjM1NDAx._V1_QL75_UY280_CR70,0,280,280_.jpg',
        role: 'Hunter B-15',
      },
      {
        name: 'Lauren Revard5 episodes5 eps • 2021',
        image:
          'https://m.media-amazon.com/images/M/MV5BZWRlYWJmMzItZWE0Zi00ZWJhLTg3YzgtMjQwM2VmYTFlY2FiXkEyXkFqcGdeQXVyMjMzNDIyNzI@._V1_QL75_UX280_CR0,0,280,280_.jpg',
        role: 'Miss Minutes On-Set Reader',
      },
      {
        name: 'Tara Strong4 episodes4 eps • 2021',
        image:
          'https://m.media-amazon.com/images/M/MV5BNjJhNjcyOWQtMjQ2My00MGU0LWFiMzItMDZlY2EzMjYwMWI3XkEyXkFqcGdeQXVyNzcwOTY0ODg@._V1_QL75_UX280_CR0,23,280,280_.jpg',
        role: 'Miss Minutes',
      },
      {
        name: 'Neil Ellice4 episodes4 eps • 2021',
        image:
          'https://m.media-amazon.com/images/M/MV5BZDExZTkzZGMtM2Y5OC00MDdjLTlhN2QtMDljYTM4OThhMGZlXkEyXkFqcGdeQXVyMzM2MDk3MzY@._V1_QL75_UX280_CR0,0,280,280_.jpg',
        role: 'Hunter D-90',
      },
      {
        name: 'Sarafina King4 episodes4 eps • 2021',
        image:
          'https://m.media-amazon.com/images/M/MV5BM2I3OWQ2OWMtNmNhYy00YjBkLTk0N2YtM2M3OWJmMmM5OTZiXkEyXkFqcGdeQXVyMjEyNzA1Nzc@._V1_QL75_UX280_CR0,24,280,280_.jpg',
        role: 'Minuteman #9',
      },
      {
        name: 'Ilan Muallem4 episodes4 eps • 2021',
        image: '',
        role: 'Minuteman #11',
      },
      {
        name: 'Sasha Lane3 episodes3 eps • 2021',
        image:
          'https://m.media-amazon.com/images/M/MV5BMTI0NmRiMDUtYzM5ZS00ZTQwLTk3OTMtZjg5OTFlMzc0NjNkL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNTI5NjIyMw@@._V1_QL75_UX280_CR0,24,280,280_.jpg',
        role: 'Hunter C-20',
      },
      {
        name: 'Philip Fornah3 episodes3 eps • 2021',
        image:
          'https://m.media-amazon.com/images/M/MV5BZDNmYzliODMtNjk2YS00YjcwLWE3YjUtOGEzMGY4YzBhNmQ2XkEyXkFqcGdeQXVyMTE1MzI1ODMx._V1_QL75_UY280_CR21,0,280,280_.jpg',
        role: 'Minuteman #1',
      },
      {
        name: 'David A MacDonald3 episodes3 eps • 2021',
        image:
          'https://m.media-amazon.com/images/M/MV5BOGIyMzJjOGMtNjA0OC00MDZmLWE4MjctOWI0OTQ3ZmQzYWY2XkEyXkFqcGdeQXVyNjAwMTg5NDU@._V1_QL75_UX280_CR0,9,280,280_.jpg',
        role: 'Minuteman #2',
      },
      {
        name: 'Michelle Rose3 episodes3 eps • 2021',
        image:
          'https://m.media-amazon.com/images/M/MV5BNmRjNTkwMDktMmI5Zi00Yjg3LTg1YzctZjk1Y2E3M2E5NDk5XkEyXkFqcGdeQXVyMTQ5MTExOTI2._V1_QL75_UX280_CR0,24,280,280_.jpg',
        role: 'Minuteman #3',
      },
      {
        name: 'Alvin Chon3 episodes3 eps • 2021',
        image:
          'https://m.media-amazon.com/images/M/MV5BMDZmNmQ0MzItN2JiZC00NGFiLTg3ZjktZTk2ZWVkNGQ5ZWYyXkEyXkFqcGdeQXVyMjQwMDg0Ng@@._V1_QL75_UX280_CR0,25,280,280_.jpg',
        role: 'Minuteman #10',
      },
      {
        name: 'Richard E. Grant2 episodes2 eps • 2021',
        image:
          'https://m.media-amazon.com/images/M/MV5BMTc2NzA1NDk1Ml5BMl5BanBnXkFtZTgwMjk2NTA0NjM@._V1_QL75_UX280_CR0,2,280,280_.jpg',
        role: 'Classic Loki',
      },
    ],
    directors: [
      { name: ' Kate Herron\n', image: 'default.png' },
      {
        name: ' Justin Benson\n',
        image: 'default.png',
      },
      { name: ' Aaron Moorhead\n', image: 'default.png' },
    ],
    genres: [{ name: 'Action' }, { name: 'Adventure' }, { name: 'Fantasy' }],
    languages: [{ name: 'English' }],
    studios: [{ name: 'Marvel Studios', image: '' }],
    writers: [
      { name: 'Tom Hiddleston', image: 'default.png' },
      {
        name: 'Owen Wilson',
        image: 'default.png',
      },
      { name: 'Eugene Cordero', image: 'default.png' },
    ],
  },
};
