version: "3.8"

volumes:
  Prometheus: {}
  PrometheusData: {}
  AlertManager: {}
  Syslog: {}
  Loki: {}
  LokiData: {}
  Promtail: {}


services:
  ############################################ Monitoring #######################################################
  ### v2.36.2
  prometheus:
    build:
      context: ./server/monitoring/prometheus
      dockerfile: Dockerfile
    container_name: prometheus
    expose:
      - 9090
    networks:
      - dio
    volumes:
      - Prometheus:/etc/prometheus
      - PrometheusData:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--storage.tsdb.retention.time=200h"
      - "--web.enable-lifecycle"
    restart: unless-stopped
    labels:
      org.label-schema.group: "monitoring"

  ### v0.24.0
  alertmanager:
    build:
      context: ./server/monitoring/alertmanager
      dockerfile: Dockerfile
    container_name: alertmanager
    volumes:
      - AlertManager:/etc/alertmanager
    command:
      - "--config.file=/etc/alertmanager/config.yml"
      - "--storage.path=/alertmanager"
    restart: unless-stopped
    expose:
      - 9093
    networks:
      - dio
    labels:
      org.label-schema.group: "monitoring"

  ### v0.44.0
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.44.0
    container_name: cadvisor
    privileged: true
    devices:
      - /dev/kmsg:/dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    restart: unless-stopped
    expose:
      - 8080
    networks:
      - dio
    labels:
      org.label-schema.group: "monitoring"

  ### v1.4.3
  pushgateway:
    image: prom/pushgateway:v1.4.3
    container_name: pushgateway
    restart: unless-stopped
    expose:
      - 9091
    networks:
      - dio
    labels:
      org.label-schema.group: "monitoring"

  ### v1.3.1
  nodeexporter:
    image: prom/node-exporter:v1.3.1
    container_name: nodeexporter
    user: root
    privileged: true
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.rootfs=/rootfs"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
    restart: unless-stopped
    expose:
      - 9100
    networks:
      - dio
    labels:
      org.label-schema.group: "monitoring"

  ### 0.10
  nginxexporter:
    image: nginx/nginx-prometheus-exporter:0.10
    container_name: nginx-exporter
    expose:
      - 9113
    command:
      - -nginx.scrape-uri
      - http://nginx:8081/stub_status
    restart: unless-stopped
    networks:
      - dio
    labels:
      org.label-schema.group: "monitoring"

  ################################################## Logging ######################################################
  ### v2.5.0
  loki:
    build:
      context: ./server/monitoring/loki
      dockerfile: Dockerfile
    container_name: loki
    privileged: true
    user: root
    volumes:
      - Loki:/etc/loki
      - LokiData:/tmp/loki
    command: -config.file=/etc/loki/loki-config.yml
    restart: always
    expose:
      - 3100
    networks:
      dio:
    labels:
      org.label-schema.group: "logging"

  ### v2.5.0
  promtail:
    build:
      context: ./server/monitoring/promtail
      dockerfile: Dockerfile
    user: root
    privileged: true
    container_name: promtail
    command: -config.file=/etc/promtail/promtail-config.yml
    volumes:
      - Promtail:/etc/promtail
      - /var/log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers
    expose:
      - 9080
      - 1514
    networks:
      dio:
    restart: unless-stopped
    labels:
      org.label-schema.group: "logging"

  # v3.30.1
  syslog-ng:
    build:
      context: ./server/monitoring/syslog
      dockerfile: Dockerfile
    container_name: syslog-ng
    user: root
    privileged: true
    volumes:
      - Syslog:/etc/syslog-ng
      - /var/log:/var/log
    networks:
      dio:
    ports:
      - protocol: udp
        published: 514
        target: 514
      - protocol: tcp
        published: 601
        target: 601
    restart: always
    labels:
      org.label-schema.group: "logging"

