GET http://localhost:4004/api/scrape/loki
Accept: application/json

###
GET http://localhost:4004/api/scrape/Dr.Strange Into The Multiverse
Accept: application/json

###
GET http://localhost:4004/api/scrape/Iron Man
Accept: application/json

###
GET http://localhost:4004/api/scrape/WandaVision
Accept: application/json

###
GET http://localhost:4004/api/scrape/dismissed
Accept: application/json

###
GET http://localhost:4004/api/scrape/uncharted
Accept: application/json

###
GET http://localhost:4004/api/scrape/dr.strange
Accept: application/json

###
GET https://localhost:2000/api/user/email/abbas.mj.srour@gmail.com/available
Accept: application/json

###
POST https://localhost:2000/api/auth/register/local
Accept: application/json
Content-Type: application/json

{
  "email": "abbas.mj.srour@gmail.com",
  "password": "NewDay12345$",
  "userName": "abbassrour",
  "confirmPassword": "NewDay12345$"
}

###
POST https://localhost:2000/api/auth/login/local
Accept: application/json
Content-Type: application/json

{
  "email": "abbas.mj.srour@gmail.com",
  "password": "NewDay12345$"
}


###
GET https://localhost:2000/api/user
Accept: application/json


