version: '3'

vars:
  SERVICE:

tasks:
  build:
    desc: Build docker service images
    cmds:
      - docker compose up {{.SERVICE}} --build
  prune:
    desc: Clear all docker data
    cmds:
      - docker system prune -a
  hercules:
    desc: Start hercules
    cmds:
      - docker compose up hercules hercules-db redis --build &
  apollo:
    desc: Start apollo
    cmds:
      - docker compose up apollo apollo-db --build &
  all:
    desc: start all services
    cmds:
      - task: apollo
      - task: hercules
      - docker compose up rabbitmq --build &
  clean:
    desc: Volume prune and remove containers
    cmds:
      - docker compose down && docker volume prune
