version: "3"

networks:
  loki:

volumes:
  progresDB:
  redisDB:
  promtail:

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4001:3000"
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "6500:5432"
    volumes:
      - progresDB:/data/postgres
    env_file:
      - ./development.env
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6479:6379"
    volumes:
      - redisDB:/data
  promtail:
    image: grafana/promtail:main
    container_name: promtail
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers
      - /home/ubuntu/docker-config.yml:/etc/promtail/docker-config.yml
    command: -config.file=/etc/promtail/docker-config.yml
    networks:
      - loki

        ###############################################################################################
version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    # depends_on:
    #   - postgres
    ports:
      - "5000:5000"
      - "9229:9229"
    # command: npm run start:docker
    # volumes:
    #   - .:/usr/app
    #   - /usr/app/node_modules

  # postgres:
  #   image: postgres:latest
  #   container_name: postgres
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgresDB:/data/postgres
  #   env_file:
  #     - ./production.env
  #     #- POSTGRES_HOST_AUTH_METHOD: trust
  #
#   redis:
#     image: redis:alpine
#     container_name: redis
#     ports:
#       - "6479:6379"
#     volumes:
#       - redisDB:/data
#
# volumes:
#   # postgresDB:
#   redisDB:
