version: "2"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "9229:9229"
    command: pnpm start:docker 
    # restart: unless-stopped
