server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

client:
  #  url: https://243977:eyJrIjoiMWM3YzgxNzE0MDc5ZjIwZjQ2MDBhN2ZlZjliMjM1NDljOWNlMWM4MyIsIm4iOiJkaW9ueXN1cy1zdHJlYW1pbmciLCJpZCI6Njc0MjI0fQ==@logs-prod-eu-west-0.grafana.net/loki/api/v1/push
  url: http://loki:3100/loki/api/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*.log
